# Generated by Django 3.0.8 on 2020-07-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.AddField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.Group'),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
