# Generated by Django 3.0.8 on 2020-07-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
